### ISSUE TITLE
layout.LayoutPreserver having problems in scaling !

### ISSUE THREAD

**Issue by Gamezpedia** [player-03/advanced-layout#4]
Hi,

i am using `.preserveChildren();` to preserve the Movieclip which i am loading from the library
but unfortunately i am not getting the exact size it looks like it is scaling twice the size of the container.

I am using it like this:
```
view = new LanguageScreenBase();
addChild(view);
view.preserveChildren();
```

Result:

The green line is the border of the container coming from Flash

![image](https://user-images.githubusercontent.com/1169093/34464397-0b45ae84-ee9f-11e7-9dee-9f30dfbbc33d.png)

or i am missing something !
thanks and happy new year

**Comment by player-03** [comment]
Hmm... I may have omitted a step. Does this help?

```haxe
view = new LanguageScreenBase();
Layout.setStageBaseDimensions(Std.int(view.width), Std.int(view.height));
addChild(view);
view.preserveChildren();
```

**Comment by Gamezpedia** [comment]
thank you for the quickest reply i am able to get the correct size of the container but the objects aren't in the middle .

![image](https://user-images.githubusercontent.com/1169093/34464516-180bf380-eea4-11e7-9360-1f7da47e6db8.png)

**Comment by Gamezpedia** [comment]
also i forgot to mention the resolution i am using in flash - is `1280 x 720`. 

**Edit:**
i thought may be if i convert all name and label to movie clips but it won't work.
then i tested with the single object in the middle and it is scaling and positioning perfectly.

but when i added more objects it lost positions.

**Comment by player-03** [comment]
Well, it's an improvement. I'll add that to the instructions.

In the meantime, can you check the exact width and height of each object? One of them might be wider than the rest of the screen, messing up the calculation of where the center is.

**Comment by Gamezpedia** [comment]
there is a bg layer filled with a white shape for the container :` 1280 x 720.`
and after the bg the biggest one is this title Movieclip : `653 x 66`

![image](https://user-images.githubusercontent.com/1169093/34464818-8bd583bc-eeb3-11e7-97d6-3999a2b5bd97.png)

i traced out every objects width and height in the console .

if i load it using responsive and on `1388 x 905` it seems closer to correct. 

![image](https://user-images.githubusercontent.com/1169093/34464839-5b305b32-eeb4-11e7-8484-c1c69504daa1.png)

but when i modify the resolution to other it looses
![image](https://user-images.githubusercontent.com/1169093/34464850-a3f2aafa-eeb4-11e7-940d-a1ce8157383c.png)

**Comment by player-03** [comment]
I guess my "intelligent" algorithm is even less intelligent than I thought. I'll have to look into it later.

Until I fix this, you'll just have to spell out where things should go:

```haxe
//Preserving the background works fine.
//(I assume that's at index 0.)
view.getChildAt(0).preserve();

//Everything else should stay near the center.
for(i in 1...view.numChildren) {
    view.getChildAt(i).stickToCenter();
}
```

**Comment by Gamezpedia** [comment]
I found the fix : [it still needs to be fixed because if you notice it is pressing the height, but i am good with the current result, will do some hacks to make it look not pressed].

i just switched to `view.preserve();` and it just scales everything correct [except height] and maintain the children's positions too.

how ever i still have an option to create the whole layout using `LayoutCreator` which works good but that is really a lengthy process for me to tackle every asset from the library. [i used that in my last game].

this game have allot of screens and i am trying to save my time :D anyways if you need more tests i will try my best to provide results. 

thanks 

```
view = new LanguageScreenBase();
Layout.setStageBaseDimensions(Std.int(view.width), Std.int(view.height));
addChild(view);
//view.preserveChildren();
view.preserve();
```
![image](https://user-images.githubusercontent.com/1169093/34464961-ba95f4d8-eeb9-11e7-81af-6a205ad65a01.png)

**Comment by Gamezpedia** [comment]
trying your fix !

the only thing worked is `view.preserve();`


**Update**
Result with : the new fix
![image](https://user-images.githubusercontent.com/1169093/34464997-cef7e808-eebb-11e7-8da3-28f0e1bfc85e.png)

**Comment by player-03** [comment]
Any chance you can send me the assets for this screen so I can play around with them?

**Comment by player-03** [comment]
If you want to send it privately, contact me [here](http://community.openfl.org/u/player_03/summary).

**Comment by Gamezpedia** [comment]
Sent you a message there !

**Comment by player-03** [comment]
Closing this since we resolved it in private.
