### ISSUE TITLE
Not compatible with Haxe 4

### ISSUE THREAD

**Issue by ConfidantCommunications** [player-03/advanced-layout#8]
I think some of the breaking changes related to static extensions in Haxe 4 are preventing this from working now. https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0

**Comment by ConfidantCommunications** [comment]
I arrived at a workaround solution here: https://community.haxe.org/t/fixing-breaking-changes-on-static-extensions-in-haxe-4/1673/4

**Comment by player-03** [comment]
Ok, I tried some macros. You should now be able to fix this by updating your `using` statements. Assuming you're using OpenFL's `DisplayObject`s, try this:

```haxe
using layout.LayoutCreator.ForOpenFL;
```

**Comment by ConfidantCommunications** [comment]
Thanks for tackling this!

First result: I had to add `import openfl.display.DisplayObjectContainer;` to make com.player03.layout.LayoutCreator work.

After that I've tested this on 2 projects. On my simplest one (modified version of AddingText from openfl-samples) I am getting this compiler message:

> /usr/lib/haxe/lib/advanced-layout/git/layout/LayoutCreator.hx:31: characters 25-58 : Invalid number of type parameters for com.player03.layout.LayoutCreator

Not sure why but my other more complex project doesn't have that error. The compiler outputs:

> /usr/lib/haxe/lib/glory/git/src/ca/confidant/glory/controller/LayoutHelper.hx:130: characters 34-55 : ca.confidant.glory.view.components.ActorComponent has no field maintainAspectRatio
> /usr/lib/haxe/lib/advanced-layout/git/com/player03/layout/item/TextSize.hx:20: characters 10-52 : Cannot access private constructor of com.player03.layout.item._TextSize.TextSizeWithMinimum
> /usr/lib/haxe/lib/advanced-layout/git/com/player03/layout/LayoutCreator.hx:671: lines 671-675 : com.player03.layout.area.Area should be openfl.display.DisplayObjectContainer

Getting closer maybe? :)

**Comment by player-03** [comment]
Two separate issues, but I think I fixed them both. How's this?

**Comment by ConfidantCommunications** [comment]
Getting close I think…
/usr/lib/haxe/lib/advanced-layout/git/com/player03/layout/item/TextSize.hx:20: characters 10-52 : Cannot access private constructor of com.player03.layout.item._TextSize.TextSizeWithMinimum

**Comment by player-03** [comment]
Huh. Interesting that they changed that, but it's an easy fix.

**Comment by ConfidantCommunications** [comment]
Hi Joseph, sorry to bug you but how's that going?

**Comment by ConfidantCommunications** [comment]
Aha, thanks!

**Comment by player-03** [comment]
Is everything working on your end now?

**Comment by ConfidantCommunications** [comment]
Yes I believe it is. Thanks for a great library! Watch for the release of Glory Framework V2!
