### ISSUE TITLE
Misleading introduction

### ISSUE THREAD

**Issue by Gama11** [player-03/advanced-layout#9]
The readme starts like this:

>An easy way to create fluid layouts in **Flash and OpenFL**.

But then later goes on to mention that other things like HaxeUI are supported too, so perhaps the phrasing could be improved a bit?

**Comment by player-03** [comment]
Hmm. This description was written back before HaxeUI added support for all the other libraries. HaxeFlixel and Punk both require OpenFL, so the description still works for them, but HaxeUI is an exception.

**Comment by player-03** [comment]
Honestly, the HaxeUI support isn't that useful. If you're using HaxeUI, you already have a way to manage layouts. I've decided to de-emphasize the feature.
